[alembic]
script_location = alembic
prepend_sys_path = .

<<<<<<< HEAD
sqlalchemy.url =

=======
>>>>>>> 921b020c2a66c4f20f03748838b59533fea97307
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
<<<<<<< HEAD
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
=======
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
>>>>>>> 921b020c2a66c4f20f03748838b59533fea97307
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
<<<<<<< HEAD
format = %(levelname)-5.5s [%(name)s] %(message)s
=======
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
>>>>>>> 921b020c2a66c4f20f03748838b59533fea97307
