"""
M11-E05 PDF building blocks.

The XLSX counterpart is app/utils/excel_export.py; this mirrors its role for
PDF so no service has to know reportlab's API directly. Everything returns
flowables, which the caller assembles into one document.
"""
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
)

BRAND = colors.HexColor("#4F81BD")
MUTED = colors.HexColor("#6B7280")
LIGHT = colors.HexColor("#F2F2F2")
BORDER = colors.HexColor("#D1D5DB")

_base = getSampleStyleSheet()

STYLES = {
    "title": ParagraphStyle("t", parent=_base["Title"], fontSize=18, textColor=BRAND, spaceAfter=4),
    "subtitle": ParagraphStyle("st", parent=_base["Normal"], fontSize=9, textColor=MUTED, spaceAfter=10),
    "h2": ParagraphStyle("h2", parent=_base["Heading2"], fontSize=12, textColor=BRAND, spaceBefore=10, spaceAfter=4),
    "body": ParagraphStyle("b", parent=_base["Normal"], fontSize=9, leading=12),
    "small": ParagraphStyle("s", parent=_base["Normal"], fontSize=7.5, textColor=MUTED, leading=10),
    "center": ParagraphStyle("c", parent=_base["Normal"], fontSize=10, alignment=TA_CENTER, textColor=MUTED),
}


def _p(text, style="body"):
    # Every value reaching a Paragraph is escaped: reportlab parses its input as
    # mini-HTML, so an unescaped "&" or "<" in free text (a rejection reason, a
    # recruiter note) raises and would take the whole export down.
    safe = (
        str(text if text not in (None, "") else "—")
        .replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    )
    return Paragraph(safe, STYLES[style])


def heading(text):
    return Paragraph(str(text), STYLES["h2"])


def title_block(title, subtitle=None):
    out = [Paragraph(str(title), STYLES["title"])]
    if subtitle:
        out.append(Paragraph(str(subtitle), STYLES["subtitle"]))
    return out


def spacer(height=6):
    return Spacer(1, height)


def key_value_table(pairs, col_widths=(55 * mm, 115 * mm)):
    """Two-column label/value block — the shape most scorecard sections take."""
    rows = [[_p(f"<b>{k}</b>"), _p(v)] for k, v in pairs]
    t = Table(rows, colWidths=list(col_widths))
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), LIGHT),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("GRID", (0, 0), (-1, -1), 0.4, BORDER),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    return t


def data_table(headers, rows, col_widths=None):
    if not rows:
        return _p("No records.", "small")
    data = [[_p(f"<b>{h}</b>") for h in headers]]
    data += [[_p(c) for c in row] for row in rows]
    t = Table(data, colWidths=col_widths, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), BRAND),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("GRID", (0, 0), (-1, -1), 0.4, BORDER),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#FAFAFA")]),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    return t


def _footer(canvas, doc):
    """Page number + confidentiality mark on every page."""
    canvas.saveState()
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(MUTED)
    canvas.drawString(15 * mm, 10 * mm, "Confidential — generated by AIRS")
    canvas.drawRightString(A4[0] - 15 * mm, 10 * mm, f"Page {canvas.getPageNumber()}")
    canvas.restoreState()


def build_pdf(flowables, title="AIRS Export") -> bytes:
    """Renders assembled flowables to PDF bytes."""
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4, title=title,
        leftMargin=15 * mm, rightMargin=15 * mm, topMargin=15 * mm, bottomMargin=18 * mm,
    )
    doc.build(list(flowables), onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()
