"""Initial schema

Revision ID: 265912f5590a
Revises: 
Create Date: 2026-07-13 12:36:37.949486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '265912f5590a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_transitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_stage', sa.Enum('UPLOADED', 'SCREENING', 'SHORTLISTED', 'HOLD', 'HM_REVIEW', 'INTERVIEW', 'SELECTED', 'REJECTED', 'FRAUD_REVIEW', name='pipeline_stage_enum'), nullable=False),
    sa.Column('to_stage', sa.Enum('UPLOADED', 'SCREENING', 'SHORTLISTED', 'HOLD', 'HM_REVIEW', 'INTERVIEW', 'SELECTED', 'REJECTED', 'FRAUD_REVIEW', name='pipeline_stage_enum'), nullable=False),
    sa.Column('allowed_roles', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('requires_reason', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_stage', 'to_stage')
    )
    op.create_table('api_rate_limit_buckets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('request_limit', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name', 'window_start')
    )
    op.create_table('circuit_breaker_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.Enum('CLOSED', 'OPEN', 'HALF_OPEN', name='cb_state_enum'), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('failure_threshold', sa.Integer(), nullable=False),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name')
    )
    op.create_table('document_processing_stage_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.Enum('JD', 'RESUME', name='document_type_enum'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.Enum('VALIDATION', 'STORAGE', 'TEXT_EXTRACTION', 'TEXT_CLEANING', 'AI_EXTRACTION', 'JSON_VALIDATION', 'SKILL_NORMALIZATION', 'EMBEDDING_GENERATION', 'PERSISTENCE', name='processing_stage_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'SKIPPED', name='stage_execution_status_enum'), nullable=False),
    sa.Column('attempt_number', sa.SmallInteger(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'stage', 'attempt_number')
    )
    op.create_table('embedding_model_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('vector_dimensions', sa.Integer(), nullable=False),
    sa.Column('distance_metric', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deprecated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_embedding_model_versions_active', 'embedding_model_versions', ['is_active'], unique=True, postgresql_where=sa.text('is_active = TRUE'))
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('embedding', Vector(dim=384), nullable=False),
    sa.Column('embedding_model_version_id', sa.UUID(), nullable=False),
    sa.Column('input_text_hash', sa.String(length=64), nullable=False),
    sa.Column('is_anonymized', sa.Boolean(), nullable=False),
    sa.Column('is_talent_pool_eligible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retention_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('last_enforced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'jurisdiction')
    )
    op.create_table('skill_ontology',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('parent_skill_id', sa.UUID(), nullable=True),
    sa.Column('embedding', Vector(dim=384), nullable=True),
    sa.Column('confidence', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_skill_id'], ['skill_ontology.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_index('idx_skill_ontology_aliases', 'skill_ontology', ['aliases'], unique=False, postgresql_using='gin')
    op.create_index('idx_skill_ontology_embedding', 'skill_ontology', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('unknown_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('normalized_key', sa.String(length=200), nullable=True),
    sa.Column('skill_suggestion_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'UNDER_REVIEW', 'MAPPED_TO_EXISTING', 'PROMOTED_TO_CANONICAL', 'DISMISSED', name='unknown_skill_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_suggestion_id'], ['skill_suggestions.id'], name='fk_unknown_skill_suggestion_id', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_text')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('HR_ADMIN', 'RECRUITER', 'HIRING_MANAGER', name='user_role_enum'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('encryption_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key_alias', sa.String(length=100), nullable=False),
    sa.Column('key_status', sa.Enum('ACTIVE', 'ROTATING', 'RETIRED', name='key_status_enum'), nullable=False),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_alias')
    )
    op.execute("""
CREATE SEQUENCE IF NOT EXISTS job_descriptions_job_id_seq
START WITH 1
INCREMENT BY 1;
""")
    op.create_table('job_descriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.String(length=50), server_default=sa.text("'JOB_' || nextval('job_descriptions_job_id_seq')"), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('extracted_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('min_experience_years', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('notice_period', sa.Integer(), nullable=True),
    sa.Column('education_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_format', sa.Enum('PDF', 'DOCX', 'TEXT', name='jd_source_format_enum'), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('is_active_version', sa.Boolean(), nullable=False),
    sa.Column('lineage_root_id', sa.UUID(), nullable=True),
    sa.Column('parent_jd_id', sa.UUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('jurisdiction', sa.String(length=10), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Enum('NOT_VERIFIED', 'PARTIALLY_VERIFIED', 'VERIFIED', name='jd_verification_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lineage_root_id'], ['job_descriptions.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_jd_id'], ['job_descriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('uq_jd_active_lineage_version', 'job_descriptions', ['lineage_root_id'], unique=True, postgresql_where=sa.text('is_active_version = TRUE'))
    op.create_table('platform_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('prompt_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('template_text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_type', 'content_hash'),
    sa.UniqueConstraint('task_type', 'version_number')
    )
    op.create_index('uq_prompt_versions_active_per_task', 'prompt_versions', ['task_type'], unique=True, postgresql_where=sa.text('is_active = TRUE'))
    op.create_table('skill_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_skill_text', sa.String(length=200), nullable=False),
    sa.Column('normalized_text', sa.String(length=200), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('unknown_skill_id', sa.UUID(), nullable=True),
    sa.Column('suggested_canonical_name', sa.String(length=100), nullable=True),
    sa.Column('suggested_parent_skill_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='skill_suggestion_status_enum'), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['suggested_parent_skill_id'], ['skill_ontology.id'], ),
    sa.ForeignKeyConstraint(['unknown_skill_id'], ['unknown_skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hiring_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('jd_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'CLOSED', name='campaign_status_enum'), nullable=False),
    sa.Column('weight_deterministic', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('weight_semantic', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('weight_ai', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('semantic_threshold', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('ai_threshold', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_candidates', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hiring_manager_id', sa.String(length=36), nullable=False),
    sa.Column('recruiter_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('weight_deterministic + weight_semantic + weight_ai = 100.00', name='chk_weights_sum_100'),
    sa.ForeignKeyConstraint(['jd_id'], ['job_descriptions.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_campaign_name_per_org')
    )
    op.create_table('jd_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jd_id', sa.UUID(), nullable=False),
    sa.Column('embedding', Vector(dim=384), nullable=False),
    sa.Column('embedding_model_version_id', sa.UUID(), nullable=False),
    sa.Column('input_text_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding_status', sa.Enum('PENDING', 'GENERATING', 'READY', 'FAILED', name='embedding_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['embedding_model_version_id'], ['embedding_model_versions.id'], ),
    sa.ForeignKeyConstraint(['jd_id'], ['job_descriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jd_id')
    )
    op.create_table('jd_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jd_id', sa.UUID(), nullable=False),
    sa.Column('canonical_skill_id', sa.UUID(), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('match_tier', sa.Text(), nullable=False),
    sa.Column('verification_status', sa.Enum('AUTO_VERIFIED', 'PENDING_REVIEW', name='jd_skill_verification_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_skill_id'], ['skill_ontology.id'], ),
    sa.ForeignKeyConstraint(['jd_id'], ['job_descriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jd_id', 'canonical_skill_id')
    )
    op.create_table('jd_unknown_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jd_id', sa.UUID(), nullable=False),
    sa.Column('unknown_skill_id', sa.UUID(), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RESOLVED', name='jd_unknown_skill_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['jd_id'], ['job_descriptions.id'], ),
    sa.ForeignKeyConstraint(['unknown_skill_id'], ['unknown_skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jd_id', 'unknown_skill_id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('action_type', sa.Enum('JD_CREATED', 'JD_UPDATED', 'JD_VERSION_CREATED', 'JD_CLOSED', 'JD_EXPORTED', 'CAMPAIGN_CREATED', 'CAMPAIGN_UPDATED', 'CAMPAIGN_SCORING_CONFIG_CHANGED', 'CAMPAIGN_PAUSED', 'CAMPAIGN_CLOSED', 'CAMPAIGN_ACTIVATED', 'CAMPAIGN_AUTO_CLOSED', 'CAMPAIGN_EDIT_BLOCKED', 'CANDIDATE_ADDED', 'CANDIDATE_UPDATED', 'CANDIDATE_REMOVED', 'JD_REPROCESSED', 'UNKNOWN_SKILL_CREATED', 'UNKNOWN_SKILL_MAPPED', 'UNKNOWN_SKILL_PROMOTED', 'UNKNOWN_SKILL_DISMISSED', 'JD_SKILL_REMAPPED', 'ALIAS_ADDED', name='audit_action_type_enum'), nullable=False),
    sa.Column('entity_type', sa.Enum('JOB_DESCRIPTION', 'CAMPAIGN', 'CAMPAIGN_CANDIDATE', 'SKILL_ONTOLOGY', 'UNKNOWN_SKILL', 'JD_SKILL', name='audit_entity_type_enum'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=10), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['hiring_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bulk_upload_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('queued_count', sa.Integer(), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'EXTRACTING', 'PROCESSING', 'COMPLETED', 'PARTIAL_FAILURE', 'FAILED', name='bulk_upload_status_enum'), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['hiring_campaigns.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('full_name_encrypted', postgresql.BYTEA(), nullable=False),
    sa.Column('email_encrypted', postgresql.BYTEA(), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=False),
    sa.Column('phone_encrypted', postgresql.BYTEA(), nullable=True),
    sa.Column('phone_hash', sa.String(length=64), nullable=True),
    sa.Column('encryption_key_id', sa.UUID(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=10), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_source', sa.String(length=100), nullable=True),
    sa.Column('source_campaign_id', sa.UUID(), nullable=True),
    sa.Column('erasure_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('erasure_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_pii_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['encryption_key_id'], ['encryption_keys.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_campaign_id'], ['hiring_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_hash')
    )
    op.create_table('search_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('queried_by', sa.String(length=255), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('query_embedding_hash', sa.String(length=64), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('top_score', sa.Numeric(precision=7, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('search_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['hiring_campaigns.id'], ),
    sa.ForeignKeyConstraint(['queried_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_consent',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_version', sa.String(length=50), nullable=False),
    sa.Column('jurisdiction', sa.String(length=10), nullable=False),
    sa.Column('consent_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consent_source', sa.String(length=100), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resumes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_format', sa.Enum('PDF', 'DOCX', 'PNG', 'JPEG', name='file_format_enum'), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('is_active_version', sa.Boolean(), nullable=False),
    sa.Column('parsed_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parse_status', sa.Enum('PENDING', 'PARSING', 'PARSED', 'FAILED', name='parse_status_enum'), nullable=False),
    sa.Column('parse_confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('parser_version', sa.String(length=50), nullable=True),
    sa.Column('page_count', sa.SmallInteger(), nullable=True),
    sa.Column('parse_duration_ms', sa.Integer(), nullable=True),
    sa.Column('ocr_used', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('pipeline_stage', sa.Enum('UPLOADED', 'SCREENING', 'SHORTLISTED', 'HOLD', 'HM_REVIEW', 'INTERVIEW', 'SELECTED', 'REJECTED', 'FRAUD_REVIEW', name='pipeline_stage_enum'), nullable=False),
    sa.Column('screened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deterministic_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('deterministic_passed', sa.Boolean(), nullable=True),
    sa.Column('semantic_score', sa.Numeric(precision=7, scale=6), nullable=True),
    sa.Column('ai_ats_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ai_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('effective_ai_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ai_recommendation', sa.Enum('SHORTLIST', 'HOLD', 'REJECT', name='ai_recommendation_enum'), nullable=True),
    sa.Column('ai_strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_evaluation_status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'MANUAL_REVIEW', name='ai_evaluation_status_enum'), nullable=False),
    sa.Column('ai_retry_count', sa.SmallInteger(), nullable=False),
    sa.Column('prompt_version_id', sa.UUID(), nullable=True),
    sa.Column('composite_score', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('fraud_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_fraud_flagged', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('rejection_layer', sa.Enum('DETERMINISTIC', 'SEMANTIC', 'AI', 'MANUAL', 'FRAUD', name='rejection_layer_enum'), nullable=True),
    sa.Column('hr_override', sa.Boolean(), nullable=False),
    sa.Column('hr_override_by', sa.String(length=255), nullable=True),
    sa.Column('hr_override_reason', sa.Text(), nullable=True),
    sa.Column('hr_override_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recruiter_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('composite_score IS NULL OR (composite_score >= 0 AND composite_score <= 100)', name='chk_composite_score_range'),
    sa.ForeignKeyConstraint(['campaign_id'], ['hiring_campaigns.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['hr_override_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'candidate_id', 'resume_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('candidate_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('canonical_skill_id', sa.UUID(), nullable=True),
    sa.Column('raw_extracted_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('match_tier', sa.Text(), nullable=False),
    sa.Column('scoring_weight', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['canonical_skill_id'], ['skill_ontology.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_candidate_skills_resume_canonical', 'candidate_skills', ['resume_id', 'canonical_skill_id'], unique=True, postgresql_where=sa.text('canonical_skill_id IS NOT NULL'))
    op.create_table('resume_parse_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.SmallInteger(), nullable=False),
    sa.Column('parser_used', sa.String(length=100), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=True),
    sa.Column('ocr_used', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'TIMEOUT', name='parse_attempt_status_enum'), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_candidate_stage_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_candidate_id', sa.UUID(), nullable=False),
    sa.Column('from_stage', sa.Enum('UPLOADED', 'SCREENING', 'SHORTLISTED', 'HOLD', 'HM_REVIEW', 'INTERVIEW', 'SELECTED', 'REJECTED', 'FRAUD_REVIEW', name='pipeline_stage_enum'), nullable=True),
    sa.Column('to_stage', sa.Enum('UPLOADED', 'SCREENING', 'SHORTLISTED', 'HOLD', 'HM_REVIEW', 'INTERVIEW', 'SELECTED', 'REJECTED', 'FRAUD_REVIEW', name='pipeline_stage_enum'), nullable=False),
    sa.Column('changed_by', sa.String(length=255), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('transition_source', sa.Enum('SYSTEM', 'MANUAL', 'TRIGGER', 'OVERRIDE', name='transition_source_enum'), nullable=False),
    sa.Column('scores_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_candidate_id'], ['campaign_candidates.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_rejections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_candidate_id', sa.UUID(), nullable=False),
    sa.Column('rejection_layer', sa.Enum('DETERMINISTIC', 'SEMANTIC', 'AI', 'MANUAL', 'FRAUD', name='rejection_layer_enum'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=False),
    sa.Column('rejection_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rejected_by', sa.String(length=255), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_candidate_id'], ['campaign_candidates.id'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('celery_task_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=True),
    sa.Column('campaign_candidate_id', sa.UUID(), nullable=True),
    sa.Column('jd_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCESS', 'FAILURE', 'RETRY', 'DEAD', name='task_status_enum'), nullable=False),
    sa.Column('retry_count', sa.SmallInteger(), nullable=False),
    sa.Column('worker_hostname', sa.String(length=255), nullable=True),
    sa.Column('input_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_candidate_id'], ['campaign_candidates.id'], ),
    sa.ForeignKeyConstraint(['jd_id'], ['job_descriptions.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('dead_letter_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_task_id', sa.String(length=255), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=True),
    sa.Column('campaign_candidate_id', sa.UUID(), nullable=True),
    sa.Column('final_error_message', sa.Text(), nullable=False),
    sa.Column('full_error_trace', sa.Text(), nullable=True),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retry_count', sa.SmallInteger(), nullable=False),
    sa.Column('first_attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('moved_to_dlq_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('replayed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replayed_by', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_candidate_id'], ['campaign_candidates.id'], ),
    sa.ForeignKeyConstraint(['original_task_id'], ['celery_task_log.task_id'], ),
    sa.ForeignKeyConstraint(['replayed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dead_letter_queue')
    op.drop_table('celery_task_log')
    op.drop_table('candidate_rejections')
    op.drop_table('campaign_candidate_stage_history')
    op.drop_table('resume_parse_attempts')
    op.drop_index('uq_candidate_skills_resume_canonical', table_name='candidate_skills', postgresql_where=sa.text('canonical_skill_id IS NOT NULL'))
    op.drop_table('candidate_skills')
    op.drop_table('campaign_candidates')
    op.drop_table('resumes')
    op.drop_table('candidate_consent')
    op.drop_table('search_queries')
    op.drop_table('candidates')
    op.drop_table('bulk_upload_jobs')
    op.drop_table('audit_log')
    op.drop_table('jd_unknown_skills')
    op.drop_table('jd_skills')
    op.drop_table('jd_embeddings')
    op.drop_table('hiring_campaigns')
    op.drop_table('skill_suggestions')
    op.drop_index('uq_prompt_versions_active_per_task', table_name='prompt_versions', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_table('prompt_versions')
    op.drop_table('platform_config')
    op.drop_index('uq_jd_active_lineage_version', table_name='job_descriptions', postgresql_where=sa.text('is_active_version = TRUE'))
    op.drop_table('job_descriptions')
    op.drop_table('encryption_keys')
    op.drop_table('users')
    op.drop_table('unknown_skills')
    op.drop_index('idx_skill_ontology_embedding', table_name='skill_ontology', postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('idx_skill_ontology_aliases', table_name='skill_ontology', postgresql_using='gin')
    op.drop_table('skill_ontology')
    op.drop_table('retention_policies')
    op.drop_table('resume_embeddings')
    op.drop_table('organizations')
    op.drop_index('uq_embedding_model_versions_active', table_name='embedding_model_versions', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_table('embedding_model_versions')
    op.drop_table('document_processing_stage_executions')
    op.drop_table('circuit_breaker_state')
    op.drop_table('api_rate_limit_buckets')
    op.drop_table('allowed_transitions')
    # ### end Alembic commands ###
