"""campaign recrutier id

Revision ID: 3ac905d10e2c
Revises: 06b5ad918767
Create Date: 2026-07-10 12:15:55.249947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ac905d10e2c'
down_revision: Union[str, Sequence[str], None] = '06b5ad918767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hiring_campaigns', sa.Column('recruiter_id', sa.String(length=36), nullable=True))
    op.alter_column('hiring_campaigns', 'hiring_manager_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=36),
               nullable=False)
    op.alter_column('hiring_campaigns', 'created_by',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_constraint(op.f('hiring_campaigns_created_by_fkey'), 'hiring_campaigns', type_='foreignkey')
    op.drop_constraint(op.f('hiring_campaigns_hiring_manager_id_fkey'), 'hiring_campaigns', type_='foreignkey')
    op.create_foreign_key('fk_unknown_skill_suggestion_id', 'unknown_skills', 'skill_suggestions', ['skill_suggestion_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_unknown_skill_suggestion_id', 'unknown_skills', type_='foreignkey')
    op.create_foreign_key(op.f('hiring_campaigns_hiring_manager_id_fkey'), 'hiring_campaigns', 'users', ['hiring_manager_id'], ['id'])
    op.create_foreign_key(op.f('hiring_campaigns_created_by_fkey'), 'hiring_campaigns', 'users', ['created_by'], ['id'])
    op.alter_column('hiring_campaigns', 'created_by',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('hiring_campaigns', 'hiring_manager_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('hiring_campaigns', 'recruiter_id')
    # ### end Alembic commands ###
