"""create campaign weight presets table

Revision ID: 793ec14a7a28
Revises: 06b5ad918767
Create Date: 2026-07-10 17:12:37.728538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '793ec14a7a28'
down_revision: Union[str, Sequence[str], None] = '06b5ad918767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_weight_presets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('weight_deterministic', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('weight_semantic', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('weight_ai', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('semantic_threshold', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ai_threshold', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_campaign_weight_presets_org_name')
    )
    op.drop_column('hiring_campaigns', 'recruiter_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hiring_campaigns', sa.Column('recruiter_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.drop_table('campaign_weight_presets')
    # ### end Alembic commands ###
