"""sync schema drift

Revision ID: d88f9123b149
Revises: a1b2c3d4e5f6
Create Date: 2026-07-14 16:56:26.206833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd88f9123b149'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    # These enum types were never created in the DB (the DB was stamped at
    # the initial-schema revision without that revision's DDL actually
    # running for them) - op.add_column/alter_column don't auto-create
    # Postgres enum types the way create_table does, so create them first.
    jd_skill_verification_status_enum = sa.Enum(
        "AUTO_VERIFIED", "PENDING_REVIEW", name="jd_skill_verification_status_enum"
    )
    jd_unknown_skill_status_enum = sa.Enum(
        "PENDING", "RESOLVED", name="jd_unknown_skill_status_enum"
    )
    unknown_skill_status_enum = sa.Enum(
        "PENDING", "UNDER_REVIEW", "MAPPED_TO_EXISTING", "PROMOTED_TO_CANONICAL", "DISMISSED",
        name="unknown_skill_status_enum",
    )
    jd_skill_verification_status_enum.create(bind, checkfirst=True)
    jd_unknown_skill_status_enum.create(bind, checkfirst=True)
    unknown_skill_status_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jd_skills', sa.Column('verification_status', jd_skill_verification_status_enum, nullable=False))
    op.add_column('jd_unknown_skills', sa.Column('mandatory', sa.Boolean(), nullable=True))
    op.add_column('jd_unknown_skills', sa.Column('status', jd_unknown_skill_status_enum, nullable=False))
    op.drop_column('job_descriptions', 'parsed_skills')
    op.execute("ALTER TABLE unknown_skills ALTER COLUMN status TYPE unknown_skill_status_enum USING status::unknown_skill_status_enum")
    op.create_foreign_key('fk_unknown_skill_suggestion_id', 'unknown_skills', 'skill_suggestions', ['skill_suggestion_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_unknown_skill_suggestion_id', 'unknown_skills', type_='foreignkey')
    op.alter_column('unknown_skills', 'status',
               existing_type=sa.Enum('PENDING', 'UNDER_REVIEW', 'MAPPED_TO_EXISTING', 'PROMOTED_TO_CANONICAL', 'DISMISSED', name='unknown_skill_status_enum'),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('job_descriptions', sa.Column('parsed_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('jd_unknown_skills', 'status')
    op.drop_column('jd_unknown_skills', 'mandatory')
    op.drop_column('jd_skills', 'verification_status')
    # ### end Alembic commands ###

    sa.Enum(name="unknown_skill_status_enum").drop(bind, checkfirst=True)
    sa.Enum(name="jd_unknown_skill_status_enum").drop(bind, checkfirst=True)
    sa.Enum(name="jd_skill_verification_status_enum").drop(bind, checkfirst=True)
