"""campaign model changes

Revision ID: ebea24c6e01a
Revises: a41e892f4a72
Create Date: 2026-07-02 14:55:40.626373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'ebea24c6e01a'
down_revision: Union[str, Sequence[str], None] = 'a41e892f4a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_ontology',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('parent_skill_id', sa.UUID(), nullable=True),
    sa.Column('embedding', Vector(dim=384), nullable=True),
    sa.Column('confidence', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_skill_id'], ['skill_ontology.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_index('idx_skill_ontology_aliases', 'skill_ontology', ['aliases'], unique=False, postgresql_using='gin')
    op.create_index('idx_skill_ontology_embedding', 'skill_ontology', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('unknown_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('normalized_key', sa.String(length=200), nullable=True),
    sa.Column('skill_suggestion_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_suggestion_id'], ['skill_suggestions.id'], name='fk_unknown_skill_suggestion_id', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_text')
    )
    op.create_table('jd_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jd_id', sa.UUID(), nullable=False),
    sa.Column('canonical_skill_id', sa.UUID(), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_skill_id'], ['skill_ontology.id'], ),
    sa.ForeignKeyConstraint(['jd_id'], ['job_descriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jd_id', 'canonical_skill_id')
    )
    op.create_table('candidate_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('canonical_skill_id', sa.UUID(), nullable=True),
    sa.Column('raw_extracted_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('match_tier', sa.Text(), nullable=False),
    sa.Column('scoring_weight', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['canonical_skill_id'], ['skill_ontology.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_candidate_skills_resume_canonical', 'candidate_skills', ['resume_id', 'canonical_skill_id'], unique=True, postgresql_where=sa.text('canonical_skill_id IS NOT NULL'))
    op.drop_table('skills')
    audit_action_type_enum = postgresql.ENUM(
        'JD_CREATED', 'JD_UPDATED', 'JD_VERSION_CREATED', 'JD_CLOSED',
        'CAMPAIGN_CREATED', 'CAMPAIGN_UPDATED', 'CAMPAIGN_PAUSED', 'CAMPAIGN_CLOSED', 'CAMPAIGN_ACTIVATED',
        name='audit_action_type_enum',
    )
    audit_action_type_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column('audit_log', 'action_type',
               existing_type=sa.VARCHAR(length=100),
               type_=audit_action_type_enum,
               existing_nullable=False,
               postgresql_using='action_type::audit_action_type_enum')

    audit_entity_type_enum = postgresql.ENUM('JOB_DESCRIPTION', 'CAMPAIGN', name='audit_entity_type_enum')
    audit_entity_type_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column('audit_log', 'entity_type',
               existing_type=sa.VARCHAR(length=100),
               type_=audit_entity_type_enum,
               existing_nullable=False,
               postgresql_using='entity_type::audit_entity_type_enum')
    op.create_index('uq_embedding_model_versions_active', 'embedding_model_versions', ['is_active'], unique=True, postgresql_where=sa.text('is_active = TRUE'))
    op.alter_column(
        "hiring_campaigns",
        "hiring_manager_id",
        existing_type=sa.UUID(),
        type_=sa.String(length=36),
        existing_nullable=False,
        postgresql_using="hiring_manager_id::text",
    )

    op.alter_column(
        "hiring_campaigns",
        "created_by",
        existing_type=sa.UUID(),
        type_=sa.String(length=36),
        existing_nullable=False,
        postgresql_using="created_by::text",
    )
    op.alter_column('hiring_campaigns', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_unique_constraint('uq_campaign_name_per_org', 'hiring_campaigns', ['org_id', 'name'])
    op.drop_constraint(op.f('hiring_campaigns_created_by_fkey'), 'hiring_campaigns', type_='foreignkey')
    op.drop_constraint(op.f('hiring_campaigns_hiring_manager_id_fkey'), 'hiring_campaigns', type_='foreignkey')
    op.create_index('uq_jd_active_lineage_version', 'job_descriptions', ['lineage_root_id'], unique=True, postgresql_where=sa.text('is_active_version = TRUE'))
    op.alter_column('platform_config', 'value',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('platform_config', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index('uq_prompt_versions_active_per_task', 'prompt_versions', ['task_type'], unique=True, postgresql_where=sa.text('is_active = TRUE'))
    op.drop_constraint(op.f('resume_embeddings_resume_id_fkey'), 'resume_embeddings', type_='foreignkey')
    op.drop_constraint(op.f('resume_embeddings_embedding_model_version_id_fkey'), 'resume_embeddings', type_='foreignkey')
    op.drop_constraint(op.f('resume_embeddings_candidate_id_fkey'), 'resume_embeddings', type_='foreignkey')
    op.add_column('skill_suggestions', sa.Column('unknown_skill_id', sa.UUID(), nullable=True))
    op.add_column('skill_suggestions', sa.Column('suggested_parent_skill_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'skill_suggestions', 'skill_ontology', ['suggested_parent_skill_id'], ['id'])
    op.create_foreign_key(None, 'skill_suggestions', 'unknown_skills', ['unknown_skill_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skill_suggestions', type_='foreignkey')
    op.drop_constraint(None, 'skill_suggestions', type_='foreignkey')
    op.drop_column('skill_suggestions', 'suggested_parent_skill_id')
    op.drop_column('skill_suggestions', 'unknown_skill_id')
    op.create_foreign_key(op.f('resume_embeddings_candidate_id_fkey'), 'resume_embeddings', 'candidates', ['candidate_id'], ['id'])
    op.create_foreign_key(op.f('resume_embeddings_embedding_model_version_id_fkey'), 'resume_embeddings', 'embedding_model_versions', ['embedding_model_version_id'], ['id'])
    op.create_foreign_key(op.f('resume_embeddings_resume_id_fkey'), 'resume_embeddings', 'resumes', ['resume_id'], ['id'])
    op.drop_index('uq_prompt_versions_active_per_task', table_name='prompt_versions', postgresql_where=sa.text('is_active = TRUE'))
    op.alter_column('platform_config', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('platform_config', 'value',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index('uq_jd_active_lineage_version', table_name='job_descriptions', postgresql_where=sa.text('is_active_version = TRUE'))
    op.create_foreign_key(op.f('hiring_campaigns_hiring_manager_id_fkey'), 'hiring_campaigns', 'users', ['hiring_manager_id'], ['id'])
    op.create_foreign_key(op.f('hiring_campaigns_created_by_fkey'), 'hiring_campaigns', 'users', ['created_by'], ['id'])
    op.drop_constraint('uq_campaign_name_per_org', 'hiring_campaigns', type_='unique')
    op.alter_column('hiring_campaigns', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('hiring_campaigns', 'created_by',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('hiring_campaigns', 'hiring_manager_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               nullable=True)
    op.drop_index('uq_embedding_model_versions_active', table_name='embedding_model_versions', postgresql_where=sa.text('is_active = TRUE'))
    op.alter_column('audit_log', 'entity_type',
               existing_type=sa.Enum('JOB_DESCRIPTION', 'CAMPAIGN', name='audit_entity_type_enum'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               postgresql_using='entity_type::text')
    postgresql.ENUM(name='audit_entity_type_enum').drop(op.get_bind(), checkfirst=True)
    op.alter_column('audit_log', 'action_type',
               existing_type=sa.Enum('JD_CREATED', 'JD_UPDATED', 'JD_VERSION_CREATED', 'JD_CLOSED', 'CAMPAIGN_CREATED', 'CAMPAIGN_UPDATED', 'CAMPAIGN_PAUSED', 'CAMPAIGN_CLOSED', 'CAMPAIGN_ACTIVATED', name='audit_action_type_enum'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               postgresql_using='action_type::text')
    postgresql.ENUM(name='audit_action_type_enum').drop(op.get_bind(), checkfirst=True)
    op.create_table('skills',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('canonical_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('parent_skill_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('occurrence_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['parent_skill_id'], ['skills.id'], name=op.f('skills_parent_skill_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('skills_pkey')),
    sa.UniqueConstraint('canonical_name', name=op.f('skills_canonical_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index('uq_candidate_skills_resume_canonical', table_name='candidate_skills', postgresql_where=sa.text('canonical_skill_id IS NOT NULL'))
    op.drop_table('candidate_skills')
    op.drop_table('jd_skills')
    op.drop_table('unknown_skills')
    op.drop_index('idx_skill_ontology_embedding', table_name='skill_ontology', postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('idx_skill_ontology_aliases', table_name='skill_ontology', postgresql_using='gin')
    op.drop_table('skill_ontology')
    # ### end Alembic commands ###
