from enum import Enum
import enum


class UserRole(str, Enum):
    HR_ADMIN       = "HR_ADMIN"
    RECRUITER      = "RECRUITER"
    HIRING_MANAGER = "HIRING_MANAGER"


class PipelineStage(str, Enum):
    APPLIED       = "APPLIED"
    SCREENING     = "SCREENING"
    SHORTLISTED   = "SHORTLISTED"
    INTERVIEW     = "INTERVIEW"
    OFFER         = "OFFER"
    HIRED         = "HIRED"
    REJECTED      = "REJECTED"


class Jurisdiction(str, Enum):
    GLOBAL = "GLOBAL"
    EU     = "EU"
    US     = "US"
    IN     = "IN"
    
    
class ActionType(enum.Enum):
    JD_CREATED= "JD_CREATED"
    JD_UPDATED= "JD_UPDATED"
    JD_VERSION_CREATED= "JD_VERSION_CREATED"
    JD_CLOSED= "JD_CLOSED"
    JD_EXPORTED= "JD_EXPORTED"
    CAMPAIGN_CREATED= "CAMPAIGN_CREATED"
    CAMPAIGN_UPDATED= "CAMPAIGN_UPDATED"
    CAMPAIGN_SCORING_CONFIG_CHANGED = "CAMPAIGN_SCORING_CONFIG_CHANGED"
    CAMPAIGN_PAUSED= "CAMPAIGN_PAUSED"
    CAMPAIGN_CLOSED= "CAMPAIGN_CLOSED"
    CAMPAIGN_ACTIVATED= "CAMPAIGN_ACTIVATED"
    CAMPAIGN_AUTO_CLOSED = "CAMPAIGN_AUTO_CLOSED"
    CAMPAIGN_EDIT_BLOCKED = "CAMPAIGN_EDIT_BLOCKED"
    CANDIDATE_ADDED = "CANDIDATE_ADDED"
    CANDIDATE_UPDATED = "CANDIDATE_UPDATED"
    CANDIDATE_REMOVED = "CANDIDATE_REMOVED"

class EntityType(enum.Enum):
    JOB_DESCRIPTION= "JOB_DESCRIPTION"
    CAMPAIGN= "CAMPAIGN"
    CAMPAIGN_CANDIDATE = "CAMPAIGN_CANDIDATE"


# Resume storage prefix inside the S3 bucket
S3_RESUME_PREFIX = "resumes/"
S3_JD_PREFIX     = "job-descriptions/"

# Embedding dimensions for all-MiniLM-L6-v2
EMBEDDING_DIM = 384

# Default pagination
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE     = 100

# API prefix — all routes must be registered under this
API_PREFIX = "/airs"
